run:
  skip-dirs:
    - pkg/sdk
  timeout: 1m

linters:
  enable-all: true
  disable:
    - godox # todo/fixme
    - godot
    - gomnd # magic number
    # - forbidigo # https://github.com/ashanbrown/forbidigo
    - nlreturn
    # - wsl
    # - testpackage
    - deadcode # replaced by unused

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - source: "^//go:generate "
      linters: [lll]
    - path: _test\.go
      linters:
        - funlen
        - lll
