run:
  skip-dirs:
    - pkg/sdk
  timeout: 1m

linters:
  enable-all: true
  disable:
    - godox # todo/fixme
    - godot # dots at the end of comments
    - gomnd # magic number
    # - forbidigo # doesn't allow to use fmt.Println
    - nlreturn # newline before return
    - wsl # forses spaces in loops, assignments, etc
    # - testpackage #  _test package
    - deadcode # replaced by unused

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - source: "^//go:generate "
      linters: [lll]
    - path: _test\.go
      linters:
        - funlen
        - lll
