linters:
  enable-all: true
  disable:
    - godox
    - godot
    - gomnd
    - forbidigo
    - nlreturn
    - wsl
    - testpackage

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - source: "^//go:generate "
      linters: [lll]
    - path: _test\.go
      linters:
        - funlen
