run:
  skip-dirs:
    - pkg/sdk
  timeout: 1m

linters:
  enable-all: true
  disable:
    - godox # todo/fixme
    - godot
    - gomnd # magic number
    - forbidigo
    - nlreturn
    - wsl
    - testpackage

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - source: "^//go:generate "
      linters: [lll]
    - path: _test\.go
      linters:
        - funlen
