run:
  skip-dirs:
    - pkg/sdk
  timeout: 1m

linters:
  enable-all: true
  disable:
    - gci
    - depguard # enforces to manually configure imports white-list
    - godox # todo/fixme
    - godot # dots at the end of comments
    - gomnd # magic number
    - nlreturn # newline before return
    - wsl # forses spaces in loops, assignments, etc
    - deadcode # replaced by unused
    - cyclop # gocyclo does this
    - exhaustivestruct
    - exhaustruct
    - exhaustive
    # - composites
    # - testpackage #  _test package
    # - forbidigo # doesn't allow to use fmt.Println

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - source: "^//go:generate"
      linters: [funlen , lll , varnamelen, err113, dupword]
    - path: _test\.go
      linters: [funlen , lll , varnamelen, err113, dupword]