run:
  timeout: 5m
  concurrency: 4
  tests: false
  skip-files:
    - ".*\\.my\\.go$"

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - source: "^//go:generate"
      linters: [funlen , lll , varnamelen, err113, dupword]
    - path: _test\.go
      linters: [funlen , lll , varnamelen, err113, dupword]