linters:
  enable-all: true
  disable:
    - godox
    - gomnd
    - forbidigo

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
