name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: build
      run: go build -v ./...
    - name: install
      run: go install ./cmd/neva/main.go
    - name: test
      run: go test -v ./...
